change to multi-keyserver checks and update formatting (non-alpine)

diff --git a/python3.6/Dockerfile b/python3.6/Dockerfile
--- a/python3.6/Dockerfile
+++ b/python3.6/Dockerfile
@@ -4,31 +4,49 @@ RUN pip install uwsgi
 
 ENV NGINX_VERSION 1.13.7-1~jessie
 
-RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 \
-    && echo "deb http://nginx.org/packages/mainline/debian/ jessie nginx" >> /etc/apt/sources.list \
-    && apt-get update \
-    && apt-get install -y ca-certificates nginx=${NGINX_VERSION} gettext-base \
+# use multiple key servers to protect against build failure
+RUN set -x \
+    && \
+    NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+    found=''; \
+    for server in \
+        ha.pool.sks-keyservers.net \
+        hkp://keyserver.ubuntu.com:80 \
+        hkp://p80.pool.sks-keyservers.net:80 \
+        pgp.mit.edu \
+    ; do \
+        echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+        apt-key adv --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+    done; \
+    test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+    echo "deb http://nginx.org/packages/mainline/debian/ jessie nginx" >> /etc/apt/sources.list \
+    && apt-get update && apt-get install -y \
+        ca-certificates \
+        nginx=${NGINX_VERSION} \
+        gettext-base \
+        supervisor \
     && rm -rf /var/lib/apt/lists/*
+
+# setup log files
 RUN ln -sf /dev/stdout /var/log/nginx/access.log \
     && ln -sf /dev/stderr /var/log/nginx/error.log
-EXPOSE 80 443
 
+# setup and copy config files
 RUN echo "daemon off;" >> /etc/nginx/nginx.conf
 RUN rm /etc/nginx/conf.d/default.conf
 COPY nginx.conf /etc/nginx/conf.d/
 COPY uwsgi.ini /etc/uwsgi/
-
-RUN apt-get update && apt-get install -y supervisor \
-    && rm -rf /var/lib/apt/lists/*
 COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
 
+# expose ports and set ENV variables
+EXPOSE 80 443
 ENV UWSGI_INI /app/uwsgi.ini
 # Enable unlimited filesize uploads (restore nginx default by setting to 1m)
 ENV NGINX_MAX_UPLOAD 0
 # Enable changing default Nginx port
 ENV LISTEN_PORT 80
 
-# entrypoint.sh generates additional Nginx configs
+# setup entrypoint.sh which generates Nginx configs at runtime
 COPY entrypoint.sh /entrypoint.sh
 RUN chmod +x /entrypoint.sh
 
